import React, { useState } from "react";
import { CreditCard, Plus, Check } from "lucide-react";

export default function PaymentSection({ paymentData, onChangePayment, isCollapsed, onEdit, onContinue, onBack }) {
  const [expandedOption, setExpandedOption] = useState(paymentData.method || "credit-card");
  const [giftCardOpen, setGiftCardOpen] = useState(false);
  const [giftCardCode, setGiftCardCode] = useState("");
  const [giftCardApplied, setGiftCardApplied] = useState(false);
  const [errors, setErrors] = useState({});
  const validate = () => { const next = {}; if (expandedOption === "credit-card" && !import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY) next.stripe = "ระบบชำระเงินยังไม่ได้ตั้งค่า Stripe"; setErrors(next); return !Object.keys(next).length; };
  const handleSubmit = (event) => { event.preventDefault(); if (validate()) { onChangePayment({ method: expandedOption }); onContinue(); } };
  const choose = (method) => { setExpandedOption(method); onChangePayment({ method }); };
  if (isCollapsed) return <div className="mb-6 rounded-lg border border-gray-200 bg-white p-5 shadow-xs"><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-bold text-gray-900">Payment</h2>{onEdit && <button type="button" onClick={onEdit} className="text-sm font-semibold underline">Edit</button>}</div><div className="flex items-center gap-3"><CreditCard className="h-5 w-5"/><span className="text-sm font-medium">{paymentData.method === "paypal" ? "PayPal" : paymentData.method === "promptpay" ? "PromptPay QR" : "ชำระผ่านบัตรเครดิต/เดบิต"}</span></div></div>;
  return <div className="mb-6 rounded-lg border border-gray-200 bg-white p-6 shadow-xs"><h2 className="mb-6 text-2xl font-bold text-gray-900">Payment</h2>
    <div className="mb-4 rounded-lg border border-gray-200 bg-white p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-bold"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-black font-serif text-xs text-white">Ω</span>Use my Gift Card</div></div>{!giftCardApplied ? <div className="mt-3"><button type="button" onClick={() => setGiftCardOpen(!giftCardOpen)} className="inline-flex items-center gap-1.5 text-xs font-semibold underline"><Plus className="h-3.5 w-3.5"/>ใส่รหัส Gift Card</button>{giftCardOpen && <div className="mt-3 flex gap-2"><input value={giftCardCode} onChange={(e) => setGiftCardCode(e.target.value)} placeholder="กรอกรหัส Gift Card หรือคูปองส่วนลด" className="flex-1 rounded border border-gray-300 px-3 py-2 text-xs"/><button type="button" onClick={() => giftCardCode.trim() && setGiftCardApplied(true)} className="rounded bg-black px-4 py-2 text-xs text-white">ใช้งาน</button></div>}</div> : <div className="mt-2 flex items-center gap-1 text-xs font-medium text-green-600"><Check className="h-4 w-4"/>ใช้ส่วนลดรหัส: {giftCardCode} เรียบร้อยแล้ว</div>}</div>
    <form onSubmit={handleSubmit} className="space-y-3">{[["paypal", "PayPal"], ["afterpay", "Afterpay"], ["klarna", "Klarna"]].map(([method, label]) => <button key={method} type="button" onClick={() => choose(method)} className="flex w-full items-center justify-between rounded-lg border border-gray-200 px-4 py-3.5 text-left hover:bg-gray-50"><span className="text-sm font-semibold">{label}</span><Plus className={`h-4 w-4 transition-transform ${expandedOption === method ? "rotate-45" : ""}`}/></button>)}
      <div className="overflow-hidden rounded-lg border border-gray-200"><button type="button" onClick={() => choose("credit-card")} className="flex w-full items-center justify-between px-4 py-3.5 text-left hover:bg-gray-50"><span className="flex items-center gap-3"><CreditCard className="h-5 w-5"/><span className="text-sm font-semibold">Credit / Debit Card</span></span><Plus className={`h-4 w-4 transition-transform ${expandedOption === "credit-card" ? "rotate-45" : ""}`}/></button>{expandedOption === "credit-card" && <div className="border-t border-gray-200 bg-gray-50 p-4 text-sm text-gray-600">ข้อมูลบัตรจะกรอกอย่างปลอดภัยผ่าน Stripe ในขั้นตอนยืนยันคำสั่งซื้อ ไม่มีการเก็บข้อมูลบัตรไว้ใน OCCASION</div>}</div>
      {errors.stripe && <p role="alert" className="text-xs text-red-600">{errors.stripe}</p>}
      <div className="flex flex-col-reverse items-center gap-3 pt-6 sm:flex-row sm:gap-4"><button type="button" onClick={onBack} className="w-full rounded-lg bg-gray-200 py-3.5 text-sm font-semibold text-gray-800 sm:w-36">ย้อนกลับ</button><button type="submit" className="w-full rounded-lg bg-[#D0021B] py-3.5 text-sm font-bold tracking-wider text-white sm:flex-1">CONTINUE</button></div>
    </form></div>;
}
